name: CI testing

on:
  push:
    branches: [ dev ]
  workflow_dispatch:

env:
  NODE_VERSION: 18.14.2

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: npm

      - name: Install dependencies
        run: npm install

      - name: Check formatting
        run: npm run format:check

      - name: Svelte check
        run: npm run check

      - name: Lint
        run: npm run lint

      - name: Test
        run: npm run test
