name: Build, test and push Docker image

# NOTE: build and test are run in the Docker image build

on:
  push:
    # main has to be restricted from normal push,
    # so this workflow runs only on a merged Pull Request
    branches: [ main ]

permissions:
  packages: write

env:
  NODE_VERSION: 18.14.2
  CONTAINER_REGISTRY: ghcr.io
  IMAGE_NAME: ci-cd-dhbw-hdh-pschoeppner/steve.heilenz/steve-heilenz

jobs:
  build-test-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: ${{ env.CONTAINER_REGISTRY }}/${{ env.IMAGE_NAME }}:${{ env.PROJECT_VERSION }}
